name: CI (Publish artifact, build and push to docker)

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v3
      with:
        name: bukkitgetter
        path: target/*-with-dependencies.jar
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: log in
      run: docker login -u mufinlive -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: true
        tags: mufinlive/bukkit-getter:latest
